#!/bin/bash

cp raw_filelist ../
cd ..
while read line
do
	name=$line
	echo "Start task of file - $name" >> finish-part.txt
	echo "Text read from file - $name"
	./sbt "run $name webfiles/"
	echo "End task of file - $name" >> finish-part.txt
done < raw_filelist
